# Generated by Django 5.0.6 on 2024-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.IntegerField(default=0)),
                ('category', models.TextField(default='none')),
                ('chapter', models.TextField(default='none')),
                ('option1', models.TextField(default='none')),
                ('option2', models.TextField(default='none')),
                ('option3', models.TextField(default='none')),
                ('option4', models.TextField(default='none')),
                ('question', models.TextField(default='none')),
                ('question_img', models.TextField(default='none')),
                ('answer', models.TextField(default='none')),
                ('danswer', models.TextField(default='none')),
                ('danswer_img', models.TextField(default='none')),
            ],
        ),
    ]
