# Generated by Django 5.0.7 on 2024-07-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='phy_easy',
        ),
    ]
