# Generated by Django 5.0.6 on 2024-07-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_enter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.TextField(default='none'),
        ),

        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='danswer',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='question',
            name='danswer_img',
            field=models.TextField(default='none'),
        )    
    ]
