# Generated by Django 5.0.7 on 2024-07-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_enter', '0002_question_answer_question_category_question_chapter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
