# Generated by Django 5.0.7 on 2024-07-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='use_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='none')),
                ('email', models.TextField(default='none')),
                ('classs', models.TextField(default='none')),
                ('category', models.TextField(default='none')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
